language: node_js
node_js:
  - '8'
after_success:
  - yarn lint || echo "Let's show the lint output here but we don't want it cause a failure yet"
  - yarn report-coverage
deploy:
  provider: npm
  email: peter@terascope.io
  api_key:
    secure: "amcbCkMKYQHtTEZN8STJPjUqIgxvwMBm87rMSOtqHiSQ1lDOOi9CLQnJDVZxfta80mdwyFdrOPahSNeFpq0SDF9c4droEJfignuGKjuxUwc68znGH4cpU8k3RNW7175Ied97g1wR1Fwt3vaOEyS3F+IrTLRvu8gb/Bcsqqv1jzAzFPrAkyGDKNY1UIQG77fgKdedyzOrsXZq5gfEW0wrxUpb6PH4LW9ojZOgtNzEdHGln6m+Ai62/IqyLzTqkQfbRoKhz5sJ5aFCputOaBcr+FyUe/btwRvmlMajURWAua+rTYfE6Uo++WzKqhIsQQDpDHfjQqkuOxpwsDuuBdJ2vk+NYMqbAz6X0uO/rjQbPe8WQ+tnRUahybv6Ze1gyMyJqlW4LYyLi+VRXm3/5UCR13YPA3+DCE3oO6BPVOD745Mwiat6CHOQEXPF529vEkxGRLHcwKkCN19p7TkZ40VcQJXQKruS/v4QiNQPdZVjSCu7t6sN5Q4Gj6RIjhgWWZvIu5QOjOcTulQDpTFaMoGFuPRwJTCeWMgvxyIvkvhO8x0CMezyQQ85Ge4PYTv5ABos83Y97RpwZ3LqAJkwv7UfmjyWkmcTq2D1W+Ey+T6o0zrDzFT/Zz6RKHJZu1/O7F0DxhKMq7tFe6Rsjc7iKAWGaBWbopOg1925QHYialtiZaM="
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
    branch: master
    repo: terascope/elasticsearch_api
